version: "3.9"
services:
  users:
    build: .
    container_name: user-microservice
    hostname: user-microservice
    networks:
      - core
    ports:
      - "4444:8080"
    environment:
      IP_HOST: ${IP_HOST}
      PORT_HOST: ${PORT_HOST}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      TOKEN_URL: ${TOKEN_URL}
      LOGOUT_URL: ${LOGOUT_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}

#QA
  users-qa:
    build: .
    container_name: user-microservice_qa
    hostname: user-microservice
    networks:
      - core-qa
    ports:
      - "24444:8080"
    environment:
      IP_HOST: ${IP_HOST}
      PORT_HOST: ${PORT_HOST_QA}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD_QA}
      CLIENT_ID: ${CLIENT_ID_QA}
      CLIENT_SECRET: ${CLIENT_SECRET_QA}
      TOKEN_URL: ${TOKEN_URL_QA}
      LOGOUT_URL: ${LOGOUT_URL_QA}
      KEYCLOAK_URL: ${KEYCLOAK_URL_QA}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM_QA}
      ISSUER_URL: ${ISSUER_URL_QA}

networks:
  core:
    driver: bridge
    external: true
  core-qa:
    driver: bridge
    external: true
