version: "3.9"
services:
  users:
    build: .
    container_name: user-microservice
    hostname: user-microservice
    networks:
      - core
    ports:
      - "4444:8080"
    environment:
      IP_HOST: ${IP_HOST}
      PORT_HOST: ${PORT_HOST}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}

#QA
  users_qa:
    build: .
    container_name: user-microservice_qa
    hostname: user-microservice
    networks:
      - core_qa
    ports:
      - "24444:8080"
    environment:
      IP_HOST: ${IP_HOST}
      PORT_HOST: ${PORT_HOST_QA}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}

networks:
  core:
    driver: bridge
    external: true
  core_qa:
    driver: bridge
    external: true