keycloak-config:
  initializeOnStartup: false
  masterRealm: master
  applicationRealm: test
  client-id: admin-cli
  username: admin
  password: ${KEYCLOAK_PASSWORD}
  url: http://keycloak:8080/

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "9090"
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator

    prefer-ip-address: true
    ip-address: "${IP_HOST}"
    nonSecurePort: "${PORT_HOST}"

spring:
  application:
    name: user-microservice


management:
  endpoints:
    web:
      exposure:
        include: "*"